name: Bug report
description: Report a bug to help us improve Undying Terminal
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.

        Before filing, please check:
        - https://undyingterminal.mintlify.app/troubleshooting/common-issues
        - https://undyingterminal.mintlify.app/troubleshooting/faq

  - type: input
    id: version
    attributes:
      label: Undying Terminal version
      description: Output of `undying-terminal.exe --version`
      placeholder: 1.0.1
    validations:
      required: true

  - type: input
    id: windows_version
    attributes:
      label: Windows version
      description: Output of `[System.Environment]::OSVersion.Version`
      placeholder: 10.0.22631.0
    validations:
      required: true

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Describe the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide clear steps.
      placeholder: |
        1. Start server with ...
        2. Start terminal with ...
        3. Connect client with ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / debug output
      description: Paste output with `$env:UT_DEBUG_HANDSHAKE=1` if possible.
      render: text
    validations:
      required: false
